apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"] # Pod に対する権限
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create"] # Service に対する権限
