apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-pods
  namespace: se-learning-hub
subjects:
  - kind: ServiceAccount
    name: default
    namespace: se-learning-hub
roleRef:
  kind: Role
  name: pod-manager # 正しくRole名を参照
  apiGroup: rbac.authorization.k8s.io
