apiVersion: v1
kind: Service
metadata:
  labels:
    app: qiita-sample-db
  name: qiita-sample-db
spec:
  ports:
    - name: 3306-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: 4qiita-sample-db
  type: ClusterIP
